# Generated by Django 2.1.5 on 2019-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190305_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
